### PR TITLE
Fix issue with CFModel.resolve

### PR DESCRIPTION
**Pull request by janeklb**
When calling `CFModel.resolve` with default `Conditions` (an empty dict, which evaluates falsy), `Conditions` is not `pop`'ed out of `dict_value`, resulting in the following error:
```
>       return CFModel(**dict_value, Conditions=resolved_conditions, Resources=resolved_resources)
E       TypeError: ModelMetaclass object got multiple values for keyword argument 'Conditions'
```

- 1st commit updates outdated actions
- 2nd commit illustrates the issue by adding a (failing) test
- 3rd commit fixes issue

### CODE REVIEW

**Review by ocrawford555 — COMMENTED** [review]
LGTM, thanks for the contribution! 👍 

Couple of questions:

- could you update the CHANGELOG for us so we can release this version post merge?
- the tests did not seem to run via GitHub actions .. not sure why that is? Would be good if we can investigate that before merging, as it is showing the second commit as passing when it shouldn't have.. 😄

**Comment by ocrawford555** [comment]
Ah the fork relationship must be the reason why the actions don't run 👍

**Comment by janeklb** [comment]
Updated Changelog!

Yes -- noticed the lack of test running 😬

**Review by ocrawford555 — APPROVED** [review]

**Review by ignaciobolonio — APPROVED** [review]
LGTM

**Pull request merged**
