### PR TITLE
Fix resolve of string-booleans to booleans instead of string

### PR DESCRIPTION
**Pull request by w0rmr1d3r**
### Fixes
- Some strings such as `"true"` or `"false"` are being resolved as `str` instead of `bool`, when they should be `bool`. It fails to resolve known models.
### Updates
- Update `CLOUDFORMATION_ACTIONS`.

### CODE REVIEW

**Review by jsoucheiron — DISMISSED** [review]
LGTM

**Review by oscarbc96 — APPROVED** [review]

**Review by oscarbc96 — CHANGES_REQUESTED** [review]
strtobool converts to True any of these values: 'y', 'yes', 't', 'true', 'on', and '1'; false values are 'n', 'no', 'f', 'false', 'off', and '0'. Raises ValueError if 'val' is anything else.

This is the same definition of pydantic bool type, bool type was changed to be strict because the standard type was too wide and was interfering with the generic behaviour. Resolve was modified accordingly on a later PR to try to fix this interference. But as stated on this PR, model parsing was broken. Adding strtobool would be a patch over a patch over a patch. 

Modifying the resolve without modifying the strict bool, would still cause some bugs.

Proposal:
- Comparations should be with the stringified values. So the last PR have to be reverted.
- StrictBool should be converted to a SemiStrictBool. Validating this doesn't interfere with Generic.

**Comment by oscarbc96** [comment]
Propose following on: https://github.com/Skyscanner/pycfmodel/pull/91

**Comment by w0rmr1d3r** [comment]
Closing this PR since it's being fixed in https://github.com/Skyscanner/pycfmodel/pull/91 instead.
Thanks @oscarbc96 for pointing it out 🚀

**Pull request closed without merging**
